/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FrixAiRouteImport } from './routes/frix-ai'
import { Route as GroupRouteImport } from './routes/group'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RequestRouteImport } from './routes/request'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as StoreRouteRouteImport } from './routes/store/route'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as BuildIndexRouteImport } from './routes/build.index'
import { Route as BuildAppRouteImport } from './routes/build.app'
import { Route as BuildWebsiteRouteImport } from './routes/build.website'
import { Route as LegalCookiesRouteImport } from './routes/legal/cookies'
import { Route as LegalDisclaimerRouteImport } from './routes/legal/disclaimer'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as StoreIndexRouteImport } from './routes/store/index'
import { Route as StoreSlugRouteImport } from './routes/store/$slug'
import { Route as StoreCheckoutRouteImport } from './routes/store/checkout'
import { Route as StoreEbooksRouteImport } from './routes/store/ebooks'
import { Route as StoreFinanceRouteImport } from './routes/store/finance'
import { Route as StoreFrixAiRouteImport } from './routes/store/frix-ai'
import { Route as StoreResourcePassRouteImport } from './routes/store/resource-pass'
import { Route as StoreTemplatesRouteImport } from './routes/store/templates'
import { Route as AuthenticatedFrixAiWorkspaceRouteImport } from './routes/_authenticated/frix-ai.workspace'
import { Route as ApiFrixAccountRouteImport } from './routes/api/frix/account'
import { Route as ApiFrixChatRouteImport } from './routes/api/frix/chat'
import { Route as ApiFrixConversationRouteImport } from './routes/api/frix/conversation'
import { Route as ApiFrixConversationsRouteImport } from './routes/api/frix/conversations'
import { Route as ApiPaystackInitializeRouteImport } from './routes/api/paystack/initialize'
import { Route as ApiPaystackStatusRouteImport } from './routes/api/paystack/status'
import { Route as ApiPaystackVerifyRouteImport } from './routes/api/paystack/verify'
import { Route as ApiPaystackWebhookRouteImport } from './routes/api/paystack/webhook'
import { Route as ApiPublicFrixRouteImport } from './routes/api/public/frix'
import { Route as ApiStoreCheckoutRouteImport } from './routes/api/store/checkout'
import { Route as ApiSubscriptionStartTrialRouteImport } from './routes/api/subscription/start-trial'
import { Route as StoreServicesIndexRouteImport } from './routes/store/services/index'
import { Route as StoreServicesSlugRouteImport } from './routes/store/services/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FrixAiRoute = FrixAiRouteImport.update({
  id: '/frix-ai',
  path: '/frix-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupRoute = GroupRouteImport.update({
  id: '/group',
  path: '/group',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRouteRoute = StoreRouteRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BuildIndexRoute = BuildIndexRouteImport.update({
  id: '/build/',
  path: '/build/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildAppRoute = BuildAppRouteImport.update({
  id: '/build/app',
  path: '/build/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildWebsiteRoute = BuildWebsiteRouteImport.update({
  id: '/build/website',
  path: '/build/website',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDisclaimerRoute = LegalDisclaimerRouteImport.update({
  id: '/legal/disclaimer',
  path: '/legal/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRouteRoute,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StoreRouteRoute,
} as any)
const StoreCheckoutRoute = StoreCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => StoreRouteRoute,
} as any)
const StoreEbooksRoute = StoreEbooksRouteImport.update({
  id: '/ebooks',
  path: '/ebooks',
  getParentRoute: () => StoreRouteRoute,
} as any)
const StoreFinanceRoute = StoreFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => StoreRouteRoute,
} as any)
const StoreFrixAiRoute = StoreFrixAiRouteImport.update({
  id: '/frix-ai',
  path: '/frix-ai',
  getParentRoute: () => StoreRouteRoute,
} as any)
const StoreResourcePassRoute = StoreResourcePassRouteImport.update({
  id: '/resource-pass',
  path: '/resource-pass',
  getParentRoute: () => StoreRouteRoute,
} as any)
const StoreTemplatesRoute = StoreTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => StoreRouteRoute,
} as any)
const AuthenticatedFrixAiWorkspaceRoute =
  AuthenticatedFrixAiWorkspaceRouteImport.update({
    id: '/frix-ai/workspace',
    path: '/frix-ai/workspace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiFrixAccountRoute = ApiFrixAccountRouteImport.update({
  id: '/api/frix/account',
  path: '/api/frix/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFrixChatRoute = ApiFrixChatRouteImport.update({
  id: '/api/frix/chat',
  path: '/api/frix/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFrixConversationRoute = ApiFrixConversationRouteImport.update({
  id: '/api/frix/conversation',
  path: '/api/frix/conversation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFrixConversationsRoute = ApiFrixConversationsRouteImport.update({
  id: '/api/frix/conversations',
  path: '/api/frix/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaystackInitializeRoute = ApiPaystackInitializeRouteImport.update({
  id: '/api/paystack/initialize',
  path: '/api/paystack/initialize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaystackStatusRoute = ApiPaystackStatusRouteImport.update({
  id: '/api/paystack/status',
  path: '/api/paystack/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaystackVerifyRoute = ApiPaystackVerifyRouteImport.update({
  id: '/api/paystack/verify',
  path: '/api/paystack/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaystackWebhookRoute = ApiPaystackWebhookRouteImport.update({
  id: '/api/paystack/webhook',
  path: '/api/paystack/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFrixRoute = ApiPublicFrixRouteImport.update({
  id: '/api/public/frix',
  path: '/api/public/frix',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreCheckoutRoute = ApiStoreCheckoutRouteImport.update({
  id: '/api/store/checkout',
  path: '/api/store/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionStartTrialRoute =
  ApiSubscriptionStartTrialRouteImport.update({
    id: '/api/subscription/start-trial',
    path: '/api/subscription/start-trial',
    getParentRoute: () => rootRouteImport,
  } as any)
const StoreServicesIndexRoute = StoreServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => StoreRouteRoute,
} as any)
const StoreServicesSlugRoute = StoreServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => StoreRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/store': typeof StoreRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/frix-ai': typeof FrixAiRoute
  '/group': typeof GroupRoute
  '/opportunities': typeof OpportunitiesRoute
  '/pricing': typeof PricingRoute
  '/request': typeof RequestRoute
  '/services': typeof ServicesRouteWithChildren
  '/solutions': typeof SolutionsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/build/app': typeof BuildAppRoute
  '/build/website': typeof BuildWebsiteRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/store/checkout': typeof StoreCheckoutRoute
  '/store/ebooks': typeof StoreEbooksRoute
  '/store/finance': typeof StoreFinanceRoute
  '/store/frix-ai': typeof StoreFrixAiRoute
  '/store/resource-pass': typeof StoreResourcePassRoute
  '/store/templates': typeof StoreTemplatesRoute
  '/build/': typeof BuildIndexRoute
  '/store/': typeof StoreIndexRoute
  '/frix-ai/workspace': typeof AuthenticatedFrixAiWorkspaceRoute
  '/api/frix/account': typeof ApiFrixAccountRoute
  '/api/frix/chat': typeof ApiFrixChatRoute
  '/api/frix/conversation': typeof ApiFrixConversationRoute
  '/api/frix/conversations': typeof ApiFrixConversationsRoute
  '/api/paystack/initialize': typeof ApiPaystackInitializeRoute
  '/api/paystack/status': typeof ApiPaystackStatusRoute
  '/api/paystack/verify': typeof ApiPaystackVerifyRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
  '/api/public/frix': typeof ApiPublicFrixRoute
  '/api/store/checkout': typeof ApiStoreCheckoutRoute
  '/api/subscription/start-trial': typeof ApiSubscriptionStartTrialRoute
  '/store/services/$slug': typeof StoreServicesSlugRoute
  '/store/services/': typeof StoreServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/frix-ai': typeof FrixAiRoute
  '/group': typeof GroupRoute
  '/opportunities': typeof OpportunitiesRoute
  '/pricing': typeof PricingRoute
  '/request': typeof RequestRoute
  '/services': typeof ServicesRouteWithChildren
  '/solutions': typeof SolutionsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/build/app': typeof BuildAppRoute
  '/build/website': typeof BuildWebsiteRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/store/checkout': typeof StoreCheckoutRoute
  '/store/ebooks': typeof StoreEbooksRoute
  '/store/finance': typeof StoreFinanceRoute
  '/store/frix-ai': typeof StoreFrixAiRoute
  '/store/resource-pass': typeof StoreResourcePassRoute
  '/store/templates': typeof StoreTemplatesRoute
  '/build': typeof BuildIndexRoute
  '/store': typeof StoreIndexRoute
  '/frix-ai/workspace': typeof AuthenticatedFrixAiWorkspaceRoute
  '/api/frix/account': typeof ApiFrixAccountRoute
  '/api/frix/chat': typeof ApiFrixChatRoute
  '/api/frix/conversation': typeof ApiFrixConversationRoute
  '/api/frix/conversations': typeof ApiFrixConversationsRoute
  '/api/paystack/initialize': typeof ApiPaystackInitializeRoute
  '/api/paystack/status': typeof ApiPaystackStatusRoute
  '/api/paystack/verify': typeof ApiPaystackVerifyRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
  '/api/public/frix': typeof ApiPublicFrixRoute
  '/api/store/checkout': typeof ApiStoreCheckoutRoute
  '/api/subscription/start-trial': typeof ApiSubscriptionStartTrialRoute
  '/store/services/$slug': typeof StoreServicesSlugRoute
  '/store/services': typeof StoreServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/store': typeof StoreRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/frix-ai': typeof FrixAiRoute
  '/group': typeof GroupRoute
  '/opportunities': typeof OpportunitiesRoute
  '/pricing': typeof PricingRoute
  '/request': typeof RequestRoute
  '/services': typeof ServicesRouteWithChildren
  '/solutions': typeof SolutionsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/build/app': typeof BuildAppRoute
  '/build/website': typeof BuildWebsiteRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/store/checkout': typeof StoreCheckoutRoute
  '/store/ebooks': typeof StoreEbooksRoute
  '/store/finance': typeof StoreFinanceRoute
  '/store/frix-ai': typeof StoreFrixAiRoute
  '/store/resource-pass': typeof StoreResourcePassRoute
  '/store/templates': typeof StoreTemplatesRoute
  '/build/': typeof BuildIndexRoute
  '/store/': typeof StoreIndexRoute
  '/_authenticated/frix-ai/workspace': typeof AuthenticatedFrixAiWorkspaceRoute
  '/api/frix/account': typeof ApiFrixAccountRoute
  '/api/frix/chat': typeof ApiFrixChatRoute
  '/api/frix/conversation': typeof ApiFrixConversationRoute
  '/api/frix/conversations': typeof ApiFrixConversationsRoute
  '/api/paystack/initialize': typeof ApiPaystackInitializeRoute
  '/api/paystack/status': typeof ApiPaystackStatusRoute
  '/api/paystack/verify': typeof ApiPaystackVerifyRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
  '/api/public/frix': typeof ApiPublicFrixRoute
  '/api/store/checkout': typeof ApiStoreCheckoutRoute
  '/api/subscription/start-trial': typeof ApiSubscriptionStartTrialRoute
  '/store/services/$slug': typeof StoreServicesSlugRoute
  '/store/services/': typeof StoreServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/store'
    | '/about'
    | '/auth'
    | '/contact'
    | '/frix-ai'
    | '/group'
    | '/opportunities'
    | '/pricing'
    | '/request'
    | '/services'
    | '/solutions'
    | '/admin'
    | '/portal'
    | '/build/app'
    | '/build/website'
    | '/legal/cookies'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/terms'
    | '/services/$slug'
    | '/store/$slug'
    | '/store/checkout'
    | '/store/ebooks'
    | '/store/finance'
    | '/store/frix-ai'
    | '/store/resource-pass'
    | '/store/templates'
    | '/build/'
    | '/store/'
    | '/frix-ai/workspace'
    | '/api/frix/account'
    | '/api/frix/chat'
    | '/api/frix/conversation'
    | '/api/frix/conversations'
    | '/api/paystack/initialize'
    | '/api/paystack/status'
    | '/api/paystack/verify'
    | '/api/paystack/webhook'
    | '/api/public/frix'
    | '/api/store/checkout'
    | '/api/subscription/start-trial'
    | '/store/services/$slug'
    | '/store/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/frix-ai'
    | '/group'
    | '/opportunities'
    | '/pricing'
    | '/request'
    | '/services'
    | '/solutions'
    | '/admin'
    | '/portal'
    | '/build/app'
    | '/build/website'
    | '/legal/cookies'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/terms'
    | '/services/$slug'
    | '/store/$slug'
    | '/store/checkout'
    | '/store/ebooks'
    | '/store/finance'
    | '/store/frix-ai'
    | '/store/resource-pass'
    | '/store/templates'
    | '/build'
    | '/store'
    | '/frix-ai/workspace'
    | '/api/frix/account'
    | '/api/frix/chat'
    | '/api/frix/conversation'
    | '/api/frix/conversations'
    | '/api/paystack/initialize'
    | '/api/paystack/status'
    | '/api/paystack/verify'
    | '/api/paystack/webhook'
    | '/api/public/frix'
    | '/api/store/checkout'
    | '/api/subscription/start-trial'
    | '/store/services/$slug'
    | '/store/services'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/store'
    | '/about'
    | '/auth'
    | '/contact'
    | '/frix-ai'
    | '/group'
    | '/opportunities'
    | '/pricing'
    | '/request'
    | '/services'
    | '/solutions'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/build/app'
    | '/build/website'
    | '/legal/cookies'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/terms'
    | '/services/$slug'
    | '/store/$slug'
    | '/store/checkout'
    | '/store/ebooks'
    | '/store/finance'
    | '/store/frix-ai'
    | '/store/resource-pass'
    | '/store/templates'
    | '/build/'
    | '/store/'
    | '/_authenticated/frix-ai/workspace'
    | '/api/frix/account'
    | '/api/frix/chat'
    | '/api/frix/conversation'
    | '/api/frix/conversations'
    | '/api/paystack/initialize'
    | '/api/paystack/status'
    | '/api/paystack/verify'
    | '/api/paystack/webhook'
    | '/api/public/frix'
    | '/api/store/checkout'
    | '/api/subscription/start-trial'
    | '/store/services/$slug'
    | '/store/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  StoreRouteRoute: typeof StoreRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FrixAiRoute: typeof FrixAiRoute
  GroupRoute: typeof GroupRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  PricingRoute: typeof PricingRoute
  RequestRoute: typeof RequestRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SolutionsRoute: typeof SolutionsRoute
  BuildAppRoute: typeof BuildAppRoute
  BuildWebsiteRoute: typeof BuildWebsiteRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalDisclaimerRoute: typeof LegalDisclaimerRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  BuildIndexRoute: typeof BuildIndexRoute
  ApiFrixAccountRoute: typeof ApiFrixAccountRoute
  ApiFrixChatRoute: typeof ApiFrixChatRoute
  ApiFrixConversationRoute: typeof ApiFrixConversationRoute
  ApiFrixConversationsRoute: typeof ApiFrixConversationsRoute
  ApiPaystackInitializeRoute: typeof ApiPaystackInitializeRoute
  ApiPaystackStatusRoute: typeof ApiPaystackStatusRoute
  ApiPaystackVerifyRoute: typeof ApiPaystackVerifyRoute
  ApiPaystackWebhookRoute: typeof ApiPaystackWebhookRoute
  ApiPublicFrixRoute: typeof ApiPublicFrixRoute
  ApiStoreCheckoutRoute: typeof ApiStoreCheckoutRoute
  ApiSubscriptionStartTrialRoute: typeof ApiSubscriptionStartTrialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frix-ai': {
      id: '/frix-ai'
      path: '/frix-ai'
      fullPath: '/frix-ai'
      preLoaderRoute: typeof FrixAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group': {
      id: '/group'
      path: '/group'
      fullPath: '/group'
      preLoaderRoute: typeof GroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/build/': {
      id: '/build/'
      path: '/build'
      fullPath: '/build/'
      preLoaderRoute: typeof BuildIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build/app': {
      id: '/build/app'
      path: '/build/app'
      fullPath: '/build/app'
      preLoaderRoute: typeof BuildAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build/website': {
      id: '/build/website'
      path: '/build/website'
      fullPath: '/build/website'
      preLoaderRoute: typeof BuildWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/disclaimer': {
      id: '/legal/disclaimer'
      path: '/legal/disclaimer'
      fullPath: '/legal/disclaimer'
      preLoaderRoute: typeof LegalDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/store/': {
      id: '/store/'
      path: '/'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/store/checkout': {
      id: '/store/checkout'
      path: '/checkout'
      fullPath: '/store/checkout'
      preLoaderRoute: typeof StoreCheckoutRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/store/ebooks': {
      id: '/store/ebooks'
      path: '/ebooks'
      fullPath: '/store/ebooks'
      preLoaderRoute: typeof StoreEbooksRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/store/finance': {
      id: '/store/finance'
      path: '/finance'
      fullPath: '/store/finance'
      preLoaderRoute: typeof StoreFinanceRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/store/frix-ai': {
      id: '/store/frix-ai'
      path: '/frix-ai'
      fullPath: '/store/frix-ai'
      preLoaderRoute: typeof StoreFrixAiRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/store/resource-pass': {
      id: '/store/resource-pass'
      path: '/resource-pass'
      fullPath: '/store/resource-pass'
      preLoaderRoute: typeof StoreResourcePassRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/store/templates': {
      id: '/store/templates'
      path: '/templates'
      fullPath: '/store/templates'
      preLoaderRoute: typeof StoreTemplatesRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/_authenticated/frix-ai/workspace': {
      id: '/_authenticated/frix-ai/workspace'
      path: '/frix-ai/workspace'
      fullPath: '/frix-ai/workspace'
      preLoaderRoute: typeof AuthenticatedFrixAiWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/frix/account': {
      id: '/api/frix/account'
      path: '/api/frix/account'
      fullPath: '/api/frix/account'
      preLoaderRoute: typeof ApiFrixAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/frix/chat': {
      id: '/api/frix/chat'
      path: '/api/frix/chat'
      fullPath: '/api/frix/chat'
      preLoaderRoute: typeof ApiFrixChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/frix/conversation': {
      id: '/api/frix/conversation'
      path: '/api/frix/conversation'
      fullPath: '/api/frix/conversation'
      preLoaderRoute: typeof ApiFrixConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/frix/conversations': {
      id: '/api/frix/conversations'
      path: '/api/frix/conversations'
      fullPath: '/api/frix/conversations'
      preLoaderRoute: typeof ApiFrixConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paystack/initialize': {
      id: '/api/paystack/initialize'
      path: '/api/paystack/initialize'
      fullPath: '/api/paystack/initialize'
      preLoaderRoute: typeof ApiPaystackInitializeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paystack/status': {
      id: '/api/paystack/status'
      path: '/api/paystack/status'
      fullPath: '/api/paystack/status'
      preLoaderRoute: typeof ApiPaystackStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paystack/verify': {
      id: '/api/paystack/verify'
      path: '/api/paystack/verify'
      fullPath: '/api/paystack/verify'
      preLoaderRoute: typeof ApiPaystackVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paystack/webhook': {
      id: '/api/paystack/webhook'
      path: '/api/paystack/webhook'
      fullPath: '/api/paystack/webhook'
      preLoaderRoute: typeof ApiPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/frix': {
      id: '/api/public/frix'
      path: '/api/public/frix'
      fullPath: '/api/public/frix'
      preLoaderRoute: typeof ApiPublicFrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store/checkout': {
      id: '/api/store/checkout'
      path: '/api/store/checkout'
      fullPath: '/api/store/checkout'
      preLoaderRoute: typeof ApiStoreCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscription/start-trial': {
      id: '/api/subscription/start-trial'
      path: '/api/subscription/start-trial'
      fullPath: '/api/subscription/start-trial'
      preLoaderRoute: typeof ApiSubscriptionStartTrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/services/': {
      id: '/store/services/'
      path: '/services'
      fullPath: '/store/services/'
      preLoaderRoute: typeof StoreServicesIndexRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/store/services/$slug': {
      id: '/store/services/$slug'
      path: '/services/$slug'
      fullPath: '/store/services/$slug'
      preLoaderRoute: typeof StoreServicesSlugRouteImport
      parentRoute: typeof StoreRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedFrixAiWorkspaceRoute: typeof AuthenticatedFrixAiWorkspaceRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedFrixAiWorkspaceRoute: AuthenticatedFrixAiWorkspaceRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface StoreRouteRouteChildren {
  StoreSlugRoute: typeof StoreSlugRoute
  StoreCheckoutRoute: typeof StoreCheckoutRoute
  StoreEbooksRoute: typeof StoreEbooksRoute
  StoreFinanceRoute: typeof StoreFinanceRoute
  StoreFrixAiRoute: typeof StoreFrixAiRoute
  StoreResourcePassRoute: typeof StoreResourcePassRoute
  StoreTemplatesRoute: typeof StoreTemplatesRoute
  StoreIndexRoute: typeof StoreIndexRoute
  StoreServicesSlugRoute: typeof StoreServicesSlugRoute
  StoreServicesIndexRoute: typeof StoreServicesIndexRoute
}

const StoreRouteRouteChildren: StoreRouteRouteChildren = {
  StoreSlugRoute: StoreSlugRoute,
  StoreCheckoutRoute: StoreCheckoutRoute,
  StoreEbooksRoute: StoreEbooksRoute,
  StoreFinanceRoute: StoreFinanceRoute,
  StoreFrixAiRoute: StoreFrixAiRoute,
  StoreResourcePassRoute: StoreResourcePassRoute,
  StoreTemplatesRoute: StoreTemplatesRoute,
  StoreIndexRoute: StoreIndexRoute,
  StoreServicesSlugRoute: StoreServicesSlugRoute,
  StoreServicesIndexRoute: StoreServicesIndexRoute,
}

const StoreRouteRouteWithChildren = StoreRouteRoute._addFileChildren(
  StoreRouteRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  StoreRouteRoute: StoreRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FrixAiRoute: FrixAiRoute,
  GroupRoute: GroupRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  PricingRoute: PricingRoute,
  RequestRoute: RequestRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SolutionsRoute: SolutionsRoute,
  BuildAppRoute: BuildAppRoute,
  BuildWebsiteRoute: BuildWebsiteRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalDisclaimerRoute: LegalDisclaimerRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  BuildIndexRoute: BuildIndexRoute,
  ApiFrixAccountRoute: ApiFrixAccountRoute,
  ApiFrixChatRoute: ApiFrixChatRoute,
  ApiFrixConversationRoute: ApiFrixConversationRoute,
  ApiFrixConversationsRoute: ApiFrixConversationsRoute,
  ApiPaystackInitializeRoute: ApiPaystackInitializeRoute,
  ApiPaystackStatusRoute: ApiPaystackStatusRoute,
  ApiPaystackVerifyRoute: ApiPaystackVerifyRoute,
  ApiPaystackWebhookRoute: ApiPaystackWebhookRoute,
  ApiPublicFrixRoute: ApiPublicFrixRoute,
  ApiStoreCheckoutRoute: ApiStoreCheckoutRoute,
  ApiSubscriptionStartTrialRoute: ApiSubscriptionStartTrialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
