/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GroupRouteImport } from './routes/group'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RequestRouteImport } from './routes/request'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as BuildIndexRouteImport } from './routes/build.index'
import { Route as BuildAppRouteImport } from './routes/build.app'
import { Route as BuildWebsiteRouteImport } from './routes/build.website'
import { Route as LegalCookiesRouteImport } from './routes/legal/cookies'
import { Route as LegalDisclaimerRouteImport } from './routes/legal/disclaimer'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ApiPaystackInitializeRouteImport } from './routes/api/paystack/initialize'
import { Route as ApiPaystackStatusRouteImport } from './routes/api/paystack/status'
import { Route as ApiPaystackVerifyRouteImport } from './routes/api/paystack/verify'
import { Route as ApiPaystackWebhookRouteImport } from './routes/api/paystack/webhook'
import { Route as ApiPublicFrixRouteImport } from './routes/api/public/frix'
import { Route as ApiSubscriptionStartTrialRouteImport } from './routes/api/subscription/start-trial'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupRoute = GroupRouteImport.update({
  id: '/group',
  path: '/group',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BuildIndexRoute = BuildIndexRouteImport.update({
  id: '/build/',
  path: '/build/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildAppRoute = BuildAppRouteImport.update({
  id: '/build/app',
  path: '/build/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildWebsiteRoute = BuildWebsiteRouteImport.update({
  id: '/build/website',
  path: '/build/website',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDisclaimerRoute = LegalDisclaimerRouteImport.update({
  id: '/legal/disclaimer',
  path: '/legal/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const ApiPaystackInitializeRoute = ApiPaystackInitializeRouteImport.update({
  id: '/api/paystack/initialize',
  path: '/api/paystack/initialize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaystackStatusRoute = ApiPaystackStatusRouteImport.update({
  id: '/api/paystack/status',
  path: '/api/paystack/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaystackVerifyRoute = ApiPaystackVerifyRouteImport.update({
  id: '/api/paystack/verify',
  path: '/api/paystack/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaystackWebhookRoute = ApiPaystackWebhookRouteImport.update({
  id: '/api/paystack/webhook',
  path: '/api/paystack/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFrixRoute = ApiPublicFrixRouteImport.update({
  id: '/api/public/frix',
  path: '/api/public/frix',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionStartTrialRoute =
  ApiSubscriptionStartTrialRouteImport.update({
    id: '/api/subscription/start-trial',
    path: '/api/subscription/start-trial',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/group': typeof GroupRoute
  '/opportunities': typeof OpportunitiesRoute
  '/pricing': typeof PricingRoute
  '/request': typeof RequestRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/build/app': typeof BuildAppRoute
  '/build/website': typeof BuildWebsiteRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/build/': typeof BuildIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/paystack/initialize': typeof ApiPaystackInitializeRoute
  '/api/paystack/status': typeof ApiPaystackStatusRoute
  '/api/paystack/verify': typeof ApiPaystackVerifyRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
  '/api/public/frix': typeof ApiPublicFrixRoute
  '/api/subscription/start-trial': typeof ApiSubscriptionStartTrialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/group': typeof GroupRoute
  '/opportunities': typeof OpportunitiesRoute
  '/pricing': typeof PricingRoute
  '/request': typeof RequestRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/build/app': typeof BuildAppRoute
  '/build/website': typeof BuildWebsiteRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/build': typeof BuildIndexRoute
  '/services': typeof ServicesIndexRoute
  '/api/paystack/initialize': typeof ApiPaystackInitializeRoute
  '/api/paystack/status': typeof ApiPaystackStatusRoute
  '/api/paystack/verify': typeof ApiPaystackVerifyRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
  '/api/public/frix': typeof ApiPublicFrixRoute
  '/api/subscription/start-trial': typeof ApiSubscriptionStartTrialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/group': typeof GroupRoute
  '/opportunities': typeof OpportunitiesRoute
  '/pricing': typeof PricingRoute
  '/request': typeof RequestRoute
  '/services': typeof ServicesRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/build/app': typeof BuildAppRoute
  '/build/website': typeof BuildWebsiteRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/build/': typeof BuildIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/paystack/initialize': typeof ApiPaystackInitializeRoute
  '/api/paystack/status': typeof ApiPaystackStatusRoute
  '/api/paystack/verify': typeof ApiPaystackVerifyRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
  '/api/public/frix': typeof ApiPublicFrixRoute
  '/api/subscription/start-trial': typeof ApiSubscriptionStartTrialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/group'
    | '/opportunities'
    | '/pricing'
    | '/request'
    | '/services'
    | '/admin'
    | '/portal'
    | '/build/app'
    | '/build/website'
    | '/legal/cookies'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/terms'
    | '/services/$slug'
    | '/build/'
    | '/services/'
    | '/api/paystack/initialize'
    | '/api/paystack/status'
    | '/api/paystack/verify'
    | '/api/paystack/webhook'
    | '/api/public/frix'
    | '/api/subscription/start-trial'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/group'
    | '/opportunities'
    | '/pricing'
    | '/request'
    | '/admin'
    | '/portal'
    | '/build/app'
    | '/build/website'
    | '/legal/cookies'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/terms'
    | '/services/$slug'
    | '/build'
    | '/services'
    | '/api/paystack/initialize'
    | '/api/paystack/status'
    | '/api/paystack/verify'
    | '/api/paystack/webhook'
    | '/api/public/frix'
    | '/api/subscription/start-trial'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/group'
    | '/opportunities'
    | '/pricing'
    | '/request'
    | '/services'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/build/app'
    | '/build/website'
    | '/legal/cookies'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/terms'
    | '/services/$slug'
    | '/build/'
    | '/services/'
    | '/api/paystack/initialize'
    | '/api/paystack/status'
    | '/api/paystack/verify'
    | '/api/paystack/webhook'
    | '/api/public/frix'
    | '/api/subscription/start-trial'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  GroupRoute: typeof GroupRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  PricingRoute: typeof PricingRoute
  RequestRoute: typeof RequestRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  BuildAppRoute: typeof BuildAppRoute
  BuildWebsiteRoute: typeof BuildWebsiteRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalDisclaimerRoute: typeof LegalDisclaimerRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  BuildIndexRoute: typeof BuildIndexRoute
  ApiPaystackInitializeRoute: typeof ApiPaystackInitializeRoute
  ApiPaystackStatusRoute: typeof ApiPaystackStatusRoute
  ApiPaystackVerifyRoute: typeof ApiPaystackVerifyRoute
  ApiPaystackWebhookRoute: typeof ApiPaystackWebhookRoute
  ApiPublicFrixRoute: typeof ApiPublicFrixRoute
  ApiSubscriptionStartTrialRoute: typeof ApiSubscriptionStartTrialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group': {
      id: '/group'
      path: '/group'
      fullPath: '/group'
      preLoaderRoute: typeof GroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/build/': {
      id: '/build/'
      path: '/build'
      fullPath: '/build/'
      preLoaderRoute: typeof BuildIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build/app': {
      id: '/build/app'
      path: '/build/app'
      fullPath: '/build/app'
      preLoaderRoute: typeof BuildAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build/website': {
      id: '/build/website'
      path: '/build/website'
      fullPath: '/build/website'
      preLoaderRoute: typeof BuildWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/disclaimer': {
      id: '/legal/disclaimer'
      path: '/legal/disclaimer'
      fullPath: '/legal/disclaimer'
      preLoaderRoute: typeof LegalDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/api/paystack/initialize': {
      id: '/api/paystack/initialize'
      path: '/api/paystack/initialize'
      fullPath: '/api/paystack/initialize'
      preLoaderRoute: typeof ApiPaystackInitializeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paystack/status': {
      id: '/api/paystack/status'
      path: '/api/paystack/status'
      fullPath: '/api/paystack/status'
      preLoaderRoute: typeof ApiPaystackStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paystack/verify': {
      id: '/api/paystack/verify'
      path: '/api/paystack/verify'
      fullPath: '/api/paystack/verify'
      preLoaderRoute: typeof ApiPaystackVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paystack/webhook': {
      id: '/api/paystack/webhook'
      path: '/api/paystack/webhook'
      fullPath: '/api/paystack/webhook'
      preLoaderRoute: typeof ApiPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/frix': {
      id: '/api/public/frix'
      path: '/api/public/frix'
      fullPath: '/api/public/frix'
      preLoaderRoute: typeof ApiPublicFrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscription/start-trial': {
      id: '/api/subscription/start-trial'
      path: '/api/subscription/start-trial'
      fullPath: '/api/subscription/start-trial'
      preLoaderRoute: typeof ApiSubscriptionStartTrialRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  GroupRoute: GroupRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  PricingRoute: PricingRoute,
  RequestRoute: RequestRoute,
  ServicesRoute: ServicesRouteWithChildren,
  BuildAppRoute: BuildAppRoute,
  BuildWebsiteRoute: BuildWebsiteRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalDisclaimerRoute: LegalDisclaimerRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  BuildIndexRoute: BuildIndexRoute,
  ApiPaystackInitializeRoute: ApiPaystackInitializeRoute,
  ApiPaystackStatusRoute: ApiPaystackStatusRoute,
  ApiPaystackVerifyRoute: ApiPaystackVerifyRoute,
  ApiPaystackWebhookRoute: ApiPaystackWebhookRoute,
  ApiPublicFrixRoute: ApiPublicFrixRoute,
  ApiSubscriptionStartTrialRoute: ApiSubscriptionStartTrialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
